package com.example.demo.mybatisTest1.model;

public class Employees {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employees.id
     *
     * @mbg.generated Wed Mar 10 12:08:11 WIB 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employees.email_address
     *
     * @mbg.generated Wed Mar 10 12:08:11 WIB 2021
     */
    private String emailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employees.first_name
     *
     * @mbg.generated Wed Mar 10 12:08:11 WIB 2021
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employees.last_name
     *
     * @mbg.generated Wed Mar 10 12:08:11 WIB 2021
     */
    private String lastName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employees.id
     *
     * @return the value of public.employees.id
     *
     * @mbg.generated Wed Mar 10 12:08:11 WIB 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employees.id
     *
     * @param id the value for public.employees.id
     *
     * @mbg.generated Wed Mar 10 12:08:11 WIB 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employees.email_address
     *
     * @return the value of public.employees.email_address
     *
     * @mbg.generated Wed Mar 10 12:08:11 WIB 2021
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employees.email_address
     *
     * @param emailAddress the value for public.employees.email_address
     *
     * @mbg.generated Wed Mar 10 12:08:11 WIB 2021
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress == null ? null : emailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employees.first_name
     *
     * @return the value of public.employees.first_name
     *
     * @mbg.generated Wed Mar 10 12:08:11 WIB 2021
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employees.first_name
     *
     * @param firstName the value for public.employees.first_name
     *
     * @mbg.generated Wed Mar 10 12:08:11 WIB 2021
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employees.last_name
     *
     * @return the value of public.employees.last_name
     *
     * @mbg.generated Wed Mar 10 12:08:11 WIB 2021
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employees.last_name
     *
     * @param lastName the value for public.employees.last_name
     *
     * @mbg.generated Wed Mar 10 12:08:11 WIB 2021
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }
}